### ISSUE TITLE
Theres a bug when I try to run it

### ISSUE THREAD

**Issue by aCrazyg1** [LewisProjects/Ogiroid#145]
It gave me this when I runned with "python main.py"
Traceback (most recent call last):
  File "/workspaces/workspace/main.py", line 20, in <module>
    main()
  File "/workspaces/workspace/main.py", line 16, in main
    bot.run(TOKEN)
  File "/usr/local/lib/python3.12/site-packages/disnake/client.py", line 1126, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/disnake/client.py", line 1105, in runner
    await self.start(*args, **kwargs)
  File "/workspaces/workspace/utils/bot.py", line 129, in start
    engine = create_async_engine(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 117, in create_async_engine
    sync_engine = _create_engine(url, **kw)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 838, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 904, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string ''
Unclosed client session
client_session: <utils.http.HTTPSession object at 0x7fe7287817c0>
Unclosed client session
client_session: <utils.http.HTTPSession object at 0x7fe726383380>

**Comment by LevaniVashadze** [comment]
Use python 3.10 and install all requirements

**Comment by aCrazyg1** [comment]
I did, with requirements.txt but it still gives me this issue

**Comment by aCrazyg1** [comment]
Traceback (most recent call last):
  File "/home/container/bot.py", line 20, in <module>
    main()
  File "/home/container/bot.py", line 16, in main
    bot.run(TOKEN)
  File "/home/container/.local/lib/python3.12/site-packages/disnake/client.py", line 1126, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/disnake/client.py", line 1105, in runner
    await self.start(*args, **kwargs)
  File "/home/container/utils/bot.py", line 129, in start
    engine = create_async_engine(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 117, in create_async_engine
    sync_engine = _create_engine(url, **kw)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/container/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 838, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 904, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string ''
Unclosed client session
client_session: <utils.http.HTTPSession object at 0x7f7dbc3ed310>
Unclosed client session
client_session: <utils.http.HTTPSession object at 0x7f7dbbc01d90>

I changed main.py to bot.py because of host

**Comment by LevaniVashadze** [comment]
Use python 3.10 as I said already
